// import React from 'react'

import Button from "../components/Button";


const Dashboard = () => {
  return (
    <div> Dashboard
      <hr></hr> 
    <Button
    className= {"bg-teal-600"}
    fullWidth = {true}
    buttonSize="small"
    > sign in </Button>
    </div>
  )
}

export default Dashboard;

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}