// import React from 'react'


const Dashboard = () => {
  return (
    <div> Dashboard </div>
  )
}

export default Dashboard;

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}